# -*- coding: utf-8 -*-
"""Homework2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/192oGicbGNs6InaulsQu91n6m-XAi8m-i
"""

# Task 1
initial_balance = 20000
annual_contribution = 10000
annual_return = 0.1
years_until_retirement = 40

balance = initial_balance

for year in range(1, years_until_retirement + 1):
    balance += annual_contribution
    balance += balance * annual_return

print(f"Balance after {years_until_retirement} years: ${balance:.2f}")



# Task 2
annual_expenses = 65000
withdrawal_rate = 0.06

target_retirement_savings = annual_expenses / withdrawal_rate

print(f"Target retirement savings: ${target_retirement_savings:.2f}")

# Task 3
balance = initial_balance
my_age = 27
retirement_age = my_age

while balance < target_retirement_savings:
    balance += annual_contribution
    balance += balance * annual_return
    retirement_age += 1

print(f"You can retire at age: {retirement_age}")
print(f"Retirement savings at age {retirement_age}: ${balance:.2f}")